"""Cambio de nombre columna

Revision ID: 328904e3fbe9
Revises: 3b812a380130
Create Date: 2023-10-26 18:14:18.936177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '328904e3fbe9'
down_revision: Union[str, None] = '3b812a380130'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('requireManagement', sa.Boolean(), nullable=True))
    op.drop_column('events', 'requireManagment')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('requireManagment', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('events', 'requireManagement')
    # ### end Alembic commands ###
